### ISSUE TITLE
trpcv10

### ISSUE THREAD

**Issue by MahmoudAlawdh** [jeeasistio/trpc-prisma#2]
[Trpc](https://trpc.io/docs/v10/quickstart) just got updated, to v10
we will update umbrella too, so i need you to take a look at it, it has some breaking changes,
upgrade this project so you get to know how it works .

**Comment by MahmoudAlawdh** [comment]
@jeeasistio

**Comment by jeeasistio** [comment]
will do sir. should i do this first before continuing on the page-purchase?

**Comment by MahmoudAlawdh** [comment]
your highest priority is page purchase, when you have free time check it out.

**Comment by jeeasistio** [comment]
yes sir.
